### ISSUE TITLE
Getting Invalid SAML Response (AuthFailed) Error

### ISSUE THREAD

**Issue by ektagoyal98** [DuendeSoftware/IdentityServer.Quickstart.UI#2]
Hi Team,
 
We are using SAML2P component of identity server for implementing external IDP authentication, in our case we have a Web application as Client, Identity Server as SP (Service Provider) and Azure AD Enterprise Application as IDP (Identity Provider).
The sign-in is working fine, but we are facing challenges in implementing single log out, for which we need help.
 
Our requirement is to achieve SLO (Single Log Out) triggered from Service Provider which is in our case Identity Server4, on logout from Identity Server we need to log out from identity server4 and thereafter from identity provider which is Okta and for some users it is Azure AD. 
 
Single Logout is working fine when we logged out from Identity Server and configure Azure AD Enterprise Application as IDP (Identity Provider), but when we configure Okta Application as IDP (Identity Provider), we are getting Invalid SAML Response (AuthFailed) Error

SAML request response is generated but getting Invalid SAML Response (AuthFailed) Error. On IDP side we are getting invalid signature error.
 
Don’t know what we are missing here or which certificate required here.
Please help us for this issue.
 
Thanks
Ekta Goyal

**Comment by leastprivilege** [comment]
The SAML2p component is from a company called RockSolidKnowledge. Please contact them if you have a support issue.

https://www.rocksolidknowledge.com/
