### ISSUE TITLE
QuickStart.UI doesn't build

### ISSUE THREAD

**Issue by marcelbeeker** [DuendeSoftware/IdentityServer.Quickstart.UI#4]
I receive an error when I try to build the Index.cshtml.cs file of the Login PageModel. The error message is on line 119. :  await HttpContext.SignInAsync(isuser, props);

Error	CS1503	Argument 2: cannot convert from 'Duende.IdentityServer.IdentityServerUser' to 'string?'	TokenServer.Web	C:\Users\marce\source\repos\TokenServer\TokenServer.Web\Duende.Quickstart.UI\Pages\Account\Login\Index.cshtml.cs	119	Active

**Comment by brockallen** [comment]
Did you read the readme?

https://github.com/DuendeSoftware/IdentityServer.Quickstart.UI#quickstart-ui-for-duende-identityserver

These are just loose files for some UI assets. You will need to build a project to compile them.

To get a new project started, you might instead consider using our templates:

https://github.com/DuendeSoftware/IdentityServer.Templates

Or follow our quickstart: 

https://docs.duendesoftware.com/identityserver/v6/quickstarts/

**Comment by marcelbeeker** [comment]
Thanks Brock helping me so quickly. Next time I will wait for any response.
I was able to solve the problem by myself using the namespaces in  your old QuickStart project.  These usings are needed to build your quickstart. 

using Duende.IdentityServer;
using Duende.IdentityServer.Events;
using Duende.IdentityServer.Models;
using Duende.IdentityServer.Services;
using Duende.IdentityServer.Stores;
using Duende.IdentityServer.Test;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Linq;
using System.Threading.Tasks;
